<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>NotePadMod</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>$(NoWarn);CS0436;CS0618</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <AmongUsDir>C:\Users\adama\OneDrive\Skrivbord\1.5.2</AmongUsDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/BepInEx.Unity.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Reactor">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/Reactor.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MiraAPI">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/MiraAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TownOfUsMira">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/TownOfUsMira.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\notepad_inactive.png" />
    <EmbeddedResource Include="Resources\notepad_active.png" />
    <EmbeddedResource Include="Resources\notepad_window.png" />
    <EmbeddedResource Include="Resources\notepad_window_black.png" />
    <EmbeddedResource Include="Resources\notepad_clear.png" />
    <EmbeddedResource Include="Resources\notepad_clear_hover.png" />
    <EmbeddedResource Include="Resources\NotepadIcon.png" />
    <EmbeddedResource Include="modinfo.json" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/" />
    <Copy
      SourceFiles="$(OutputPath)$(AssemblyName).dll"
      DestinationFolder="/Users/neiljain/Documents/GitHub/Mira-NotePad/libs/"
      SkipUnchangedFiles="false" />
    <Message Text="DLL kopierad till plugins!" Importance="high" />
  </Target>
</Project>
